#!/bin/bash -l

#SBATCH --job-name=fixsafir # Job name
#SBATCH --partition=cpu # Partition
#SBATCH --nodes=1 # Number of nodes
#SBATCH --ntasks-per-node=1  # Number of tasks
#SBATCH --output=%j.out # Stdout (%j=jobId)
#SBATCH --error=%j.err # Stderr (%j=jobId)
#SBATCH --mem=64000
#SBATCH --time=24:00:00 # Walltime
#SBATCH -A p118

module load Zip/3.0-GCCcore-11.2.0

zip -FF assafir-images.zip --out repaired.zip
