#!/bin/bash -l

#SBATCH --job-name=gather # Job name
#SBATCH --partition=cpu # Partition
#SBATCH --nodes=1 # Number of nodes
#SBATCH --ntasks-per-node=1  # Number of tasks
#SBATCH --output=%j.out # Stdout (%j=jobId)
#SBATCH --error=%j.err # Stderr (%j=jobId)
#SBATCH --mem=1000
#SBATCH --time=1:00:00 # Walltime
#SBATCH -A p118

# Load any necessary modules
module purge
module load Python/3.7.4-GCCcore-8.3.0

python gather_opinionated_pdfs.py
