#!/bin/bash -l

#SBATCH --job-name=mlm # Job name
#SBATCH --partition=gpu # Partition
#SBATCH --nodes=1 # Number of nodes
#SBATCH --gres=gpu:1 # Number of GPUs
#SBATCH --ntasks-per-node=1  # Number of tasks
#SBATCH --output=%j.out # Stdout (%j=jobId)
#SBATCH --error=%j.err # Stderr (%j=jobId)
#SBATCH --mem=180000
#SBATCH --time=23:00:00 # Walltime
#SBATCH -A p118

export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

# Load any necessary modules, in this case OpenMPI with CUDA
# module purge
# module load Java/11.0.16
# module load Python/3.10.4-GCCcore-11.3.0
# module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0

module purge
source /nvme/h/lb21hg1/hiyam3.11venv/bin/activate

python main.py