#!/bin/bash -l

#SBATCH --job-name=mlm # Job name
#SBATCH --partition=gpu # Partition
#SBATCH --nodes=1 # Number of nodes
#SBATCH --gres=gpu:1 # Number of GPUs
#SBATCH --ntasks-per-node=1  # Number of tasks
#SBATCH --output=%j.out # Stdout (%j=jobId)
#SBATCH --error=%j.err # Stderr (%j=jobId)
#SBATCH --mem=120000
#SBATCH --time=23:00:00 # Walltime
#SBATCH -A p118
#SBATCH --array=1-6%5

# Load any necessary modules, in this case OpenMPI with CUDA
module purge
module load Java/11.0.16
module load Python/3.10.4-GCCcore-11.3.0
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0


python main2.py $(head -n $SLURM_ARRAY_TASK_ID jobs.txt | tail -n 1)